# Generated by Django 5.1.2 on 2024-11-18 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=200)),
                ('categories', models.JSONField(default=list)),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
                ('prioritized', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='EventsAvailable',
        ),
    ]
