# Generated by Django 5.1.2 on 2024-11-18 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapis', '0002_locations_delete_eventsavailable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
