# Generated by Django 5.1.2 on 2024-11-22 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapis', '0003_alter_locations_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='allowsDogs',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='locations',
            name='goodForChildren',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='locations',
            name='goodForGroups',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='locations',
            name='hours',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AddField(
            model_name='locations',
            name='priceLevel',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='locations',
            name='priceMax',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='locations',
            name='priceMin',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='locations',
            name='rating',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='locations',
            name='address',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='locations',
            name='name',
            field=models.CharField(blank=True, null=True),
        ),
    ]
