# Generated by Django 5.1.2 on 2024-12-08 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapis', '0004_locations_allowsdogs_locations_goodforchildren_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='categories_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locations',
            name='hours_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
